map ctrl+shift+ú launch --location=vsplit
map ctrl+shift+- launch --location=hsplit

enabled_layouts splits,stack

term xterm

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

font_size 14.0

auto_reload_config -1
