# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/983b320b-bd11-4de7-a8cc-2de24eb8801e";
      fsType = "btrfs";
      options = [ "compress=zstd:3" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/983b320b-bd11-4de7-a8cc-2de24eb8801e";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/983b320b-bd11-4de7-a8cc-2de24eb8801e";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4A4A-7A28";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
