#!/usr/bin/env bash
IFACE="${1:?Usage: pktlog <interface>}"
PATH="/run/wrappers/bin:$PATH"
exec tshark -i "$IFACE" -l -q \
  -T fields \
  -e frame.time \
  -e _ws.col.Source \
  -e _ws.col.Destination \
  -e _ws.col.Protocol \
  -e _ws.col.Info \
  -E separator="|" -E header=y
